#pragma once
#ifndef INCLUDE_GUARD_OMNIXLIB_CONFIG_HEADER_
#define INCLUDE_GUARD_OMNIXLIB_CONFIG_HEADER_

#define OXLIBCONFIG_USE_EXPLICIT_TYPEDEF 0
#define OXLIBCONFIG_DONT_USE_OX_NAMESPACE 0
#define OXLIBCONFIG_USE_NESTED_NAMESPACES 1

#define OXLIBCONFIG_SET
#endif